### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by SpiralDeveloper** [irshuLx/Android-WYSIWYG-Editor#39]
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2560)
                                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2626)
                                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1475)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                               at android.os.Looper.loop(Looper.java:207)
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:5740)
                                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
                                                                                            Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                                               at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:260)
                                                                                               at java.util.ArrayList.get(ArrayList.java:313)
                                                                                               at org.jsoup.select.Elements.get(Elements.java:544)
                                                                                               at org.jsoup.nodes.Element.child(Element.java:171)
                                                                                               at com.github.irshulx.Components.HTMLExtensions.RenderImage(HTMLExtensions.java:78)
                                                                                               at com.github.irshulx.Components.HTMLExtensions.buildNode(HTMLExtensions.java:63)
                                                                                               at com.github.irshulx.Components.HTMLExtensions.parseHtml(HTMLExtensions.java:33)
                                                                                               at com.github.irshulx.EditorCore.renderEditorFromHtml(EditorCore.java:538)
                                                                                               at com.github.irshulx.Editor.render(Editor.java:75)

**Comment by irshuLx** [comment]
Sorry for the late reply. When this issue happens, please paste the HTML as well so we can use it to test and find the cause, thanks.
