### ISSUE TITLE
What is the Proguard rules?

### ISSUE THREAD

**Issue by TayfunCesur** [irshuLx/Android-WYSIWYG-Editor#54]
Hey. Firstly, thank you for this amazing library. But When use minify enable, what proguard rules am      I have to use ?. This error coming from jsoup I think. Stack trace is below. Thanks!

` 

        at org.a.b.h.a(Entities.java:18)
        at org.a.b.h$a.<clinit>(Entities.java:21) 
        at org.a.b.e$a.<init>(Document.java:226) 
        at org.a.b.e.<init>(Document.java:18) 
        at org.a.c.l.b(TreeBuilder.java:27) 
        at org.a.c.l.a(TreeBuilder.java:40) 
        at org.a.c.b.a(HtmlTreeBuilder.java:55) 
        at org.a.c.f.a(Parser.java:90)
        at org.a.a.a(Jsoup.java:58)
        at com.github.irshulx.Components.HTMLExtensions.parseHtml(HTMLExtensions.java:29)
        at com.github.irshulx.EditorCore.renderEditorFromHtml(EditorCore.java:543)
        at com.github.irshulx.Editor.render(Editor.java:76)`

**Comment by irshuLx** [comment]
Can try with the following rule?

` -keep public class org.jsoup.** {
 public *;
 }`

**Comment by TayfunCesur** [comment]
It worked like charm! Thank you
