### ISSUE TITLE
Exception on InsertLink When current line is empty

### ISSUE THREAD

**Issue by gonbad** [irshuLx/Android-WYSIWYG-Editor#6]
`java.lang.StringIndexOutOfBoundsException: length=0; index=-1
                      at java.lang.String.indexAndLength(String.java:500)
                      at java.lang.String.charAt(String.java:494)
                      at com.github.irshulx.Components.InputExtensions.trimLineEnding(InputExtensions.java:428)
                      at com.github.irshulx.Components.InputExtensions.InsertLink(InputExtensions.java:401)
                      at com.github.irshulx.Components.InputExtensions.access$000(InputExtensions.java:50)
                      at com.github.irshulx.Components.InputExtensions$5.onClick(InputExtensions.java:383)`

**Comment by gonbad** [comment]
thanks
