### ISSUE TITLE
Crash with Glide No super method apply(Lcom/bumptech/glide/request/RequestOptions;)

### ISSUE THREAD

**Issue by elfadl** [irshuLx/Android-WYSIWYG-Editor#71]
I don't know where is the wrong. I think it was in glide dependency. But the logical said that crash caused at com.github.irshulx.GlideOptions.apply(GlideOptions.java:605). When I downgrade the version to 2.3.2 (used Picasso), it's going normal again. But some feature can't be use and also cause crash.

this is my code that call Glide dependency : 

`Glide.with(imageView.getContext()).load(image).apply(bitmapTransform(new RoundedCorners(4))).into(imageView);`

this is my logcat :

```
E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
    java.lang.NoSuchMethodError: No super method apply(Lcom/bumptech/glide/request/RequestOptions;)Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/id.inovativo.bmi_sukses-1/split_lib_dependencies_apk.apk)
        at com.github.irshulx.GlideOptions.apply(GlideOptions.java:605)
        at com.github.irshulx.GlideRequests.setRequestOptions(GlideRequests.java:170)
        at com.bumptech.glide.RequestManager.<init>(RequestManager.java:136)
        at com.bumptech.glide.RequestManager.<init>(RequestManager.java:94)
        at com.github.irshulx.GlideRequests.<init>(GlideRequests.java:38)
        at com.bumptech.glide.GeneratedRequestManagerFactory.build(GeneratedRequestManagerFactory.java:19)
        at com.bumptech.glide.manager.RequestManagerRetriever.supportFragmentGet(RequestManagerRetriever.java:441)
        at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:134)
        at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:116)
        at com.bumptech.glide.Glide.with(Glide.java:716)
        at id.inovativo.bmi_sukses.viewmodel.FontBinding.setImg(FontBinding.java:30)
        at id.inovativo.bmi_sukses.databinding.LayoutSliderBindingImpl.executeBindings(LayoutSliderBindingImpl.java:127)
        at android.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:471)
        at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:443)
        at android.databinding.ViewDataBinding$7.run(ViewDataBinding.java:195)
        at android.databinding.ViewDataBinding$8.doFrame(ViewDataBinding.java:289)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:792)
        at android.view.Choreographer.doCallbacks(Choreographer.java:607)
        at android.view.Choreographer.doFrame(Choreographer.java:574)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:780)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5304)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
```

**Comment by irshuLx** [comment]
I've updated glide to 4.9.0. Please try again. #72

**Comment by UrbanSide** [comment]
I have this error too on 4.9.0

**Comment by zarksalman** [comment]
I'm also getting this error:
Glide version: com.github.bumptech.glide:glide:4.9.0
This library version: com.github.irshulx:laser-native-editor:3.0.3

**Comment by UrbanSide** [comment]
> I'm also getting this error:
> Glide version: com.github.bumptech.glide:glide:4.9.0
> This library version: com.github.irshulx:laser-native-editor:3.0.3

change **com.github.irshulx:laser-native-editor:3.0.3** to **com.github.irshulx:laser-native-editor:3.0.4**
And use force fix **com.github.bumptech.glide:glide:4.9.0** in you gradle file

**Comment by manacy** [comment]
> I'm also getting this error:
> Glide version: com.github.bumptech.glide:glide:4.9.0
> This library version: com.github.irshulx:laser-native-editor:3.0.3

worked for me
