### ISSUE TITLE
Glide 9.4.0 error

### ISSUE THREAD

**Issue by UrbanSide** [irshuLx/Android-WYSIWYG-Editor#86]
```
Fatal Exception: java.lang.NoSuchMethodError: No virtual method placeholder(I)Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in base.apk)
       at com.github.irshulx.Components.ImageExtensions.loadImageUsingLib(ImageExtensions.java:346)
       at com.github.irshulx.Components.ImageExtensions.loadImageRemote(ImageExtensions.java:307)
       at com.github.irshulx.Components.ImageExtensions.loadImage(ImageExtensions.java:289)
       at com.github.irshulx.Components.ImageExtensions.buildNodeFromHTML(ImageExtensions.java:132)
       at com.github.irshulx.EditorCore.buildNodeFromHTML(EditorCore.java:461)
       at com.github.irshulx.EditorCore.parseHtml(EditorCore.java:419)
       at com.github.irshulx.EditorCore.renderEditorFromHtml(EditorCore.java:515)
       at com.github.irshulx.Editor.render(Editor.java:79)
       at com.box.a100rados.Activity.BlogTest.onCreate(BlogTest.java:20)
       at android.app.Activity.performCreate(Activity.java:7224)
       at android.app.Activity.performCreate(Activity.java:7213)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by UrbanSide** [comment]
With force 4.9.0 i have this error
```
Fatal Exception: java.lang.NoSuchMethodError: No virtual method placeholder(I)Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in base.apk)
       at com.github.irshulx.Components.ImageExtensions.loadImageUsingLib(ImageExtensions.java:346)
       at com.github.irshulx.Components.ImageExtensions.loadImageRemote(ImageExtensions.java:307)
       at com.github.irshulx.Components.ImageExtensions.loadImage(ImageExtensions.java:289)
       at com.github.irshulx.Components.ImageExtensions.buildNodeFromHTML(ImageExtensions.java:132)
       at com.github.irshulx.EditorCore.buildNodeFromHTML(EditorCore.java:461)
       at com.github.irshulx.EditorCore.parseHtml(EditorCore.java:419)
       at com.github.irshulx.EditorCore.renderEditorFromHtml(EditorCore.java:515)
       at com.github.irshulx.Editor.render(Editor.java:79)
       at com.box.a100rados.Activity.BlogTest.onCreate(BlogTest.java:20)
       at android.app.Activity.performCreate(Activity.java:7224)
       at android.app.Activity.performCreate(Activity.java:7213)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by UrbanSide** [comment]
Fix this by upgrade version to 3.0.4 in readme was 3.0.3
